site_name: Medizin Lexikon
site_url: https://lexikon-web.netlify.app   # optional, kannst du später anpassen
theme:
  name: material
  language: de
  features:
    - navigation.instant     # Seitenwechsel ohne komplettes Reload
    - navigation.top         # "Zurück nach oben"-Button
    - search.suggest         # Vorschläge in der Suche
    - search.highlight       # Suchbegriffe im Text hervorheben
    - content.code.copy      # Kopier-Button bei Codeblöcken
nav:
  - Home: index.md
  - Index: index_all.md

plugins:
  - search
  - glightbox
  - gen-files:
      scripts:
        - scripts/generate_index.py

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - footnotes
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - styles/extra.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js
