site_name: Medizin Lexikon
site_url: https://lexikon-web.netlify.app   # optional, kannst du später anpassen
theme:
  name: material
  language: de
  features:
    - navigation.instant     # Seitenwechsel ohne komplettes Reload
    - navigation.top         # "Zurück nach oben"-Button
    - search.suggest         # Vorschläge in der Suche
    - search.highlight       # Suchbegriffe im Text hervorheben
    - content.code.copy      # Kopier-Button bei Codeblöcken
nav:
  - Home: index.md
  - Index: index_all.md

plugins:
  - search
  - callouts
  - glightbox
  - gen-files:
      scripts:
        - docs/scripts/generate_index_grid.py

markdown_extensions:
  - admonition
  - nl2br
  - tables
  - toc:
      permalink: true
  - footnotes
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - styles/extra.css
  - styles/admonitions.css
  - styles/grid.css


extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - scripts/config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
